CI: fix deployment of Rocky 9 images
CI deployment has begun failing:

  AssertionError: missing artifact: rocky_9.7_graphviz-15.1.0~dev.20260616.1721-rpms.tar.xz

It seems a8f90d40b66522e2d9a7a57bf26fbea0b8fdef97 upgraded Rocky
9.7 → 9.8.