common font_item_t.action: take 'v' as const
This is a step towards removing a function pointer cast that is causing
problems on macOS:

  lib/common/htmllex.c:778:6: error: cast from 'void (*)(void *, const
    char *, char **)' to 'XML_StartElementHandler' (aka 'void
    (*)(void *, const char *, const char **)') converts to incompatible
    function type [-Werror,-Wcast-function-type-strict]
  778 |                        (XML_StartElementHandler) startElement,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This introduces two -Wcast-qual warnings, which hopefully can be paid
down in future.

Gitlab: #2840
Reported-by: Apple Clang 17.0.0.17000013 -Wcast-function-type-strict