gvedit: remove unused 'CFrmSettings' fields
It is unclear to me why 4df89cce1d9b2e31d29e0bd92c557df6712dae68
replicated these fields from cmd/gvedit/mainwindow.h. These are now
causing macOS builds to fail:

  cmd/gvedit/csettings.h:47:14: error: private field 'outputAct' is not used [-Werror,-Wunused-private-field]
     47 |     QAction* outputAct;
        |              ^
  cmd/gvedit/csettings.h:48:14: error: private field 'addAct' is not used [-Werror,-Wunused-private-field]
     48 |     QAction* addAct;
        |              ^
  cmd/gvedit/csettings.h:49:14: error: private field 'helpAct' is not used [-Werror,-Wunused-private-field]
     49 |     QAction* helpAct;
        |              ^
  cmd/gvedit/csettings.h:50:14: error: private field 'cancelAct' is not used [-Werror,-Wunused-private-field]
     50 |     QAction* cancelAct;
        |              ^
  cmd/gvedit/csettings.h:51:14: error: private field 'okAct' is not used [-Werror,-Wunused-private-field]
     51 |     QAction* okAct;
        |              ^
  cmd/gvedit/csettings.h:52:14: error: private field 'newAct' is not used [-Werror,-Wunused-private-field]
     52 |     QAction* newAct;
        |              ^
  cmd/gvedit/csettings.h:53:14: error: private field 'openAct' is not used [-Werror,-Wunused-private-field]
     53 |     QAction* openAct;
        |              ^
  cmd/gvedit/csettings.h:54:14: error: private field 'saveAct' is not used [-Werror,-Wunused-private-field]
     54 |     QAction* saveAct;
        |              ^

Gitlab: #2842, !4960, #2853
Reported-by: AppleClang 17.0.0.17000013 -Wunused-private-field