gvedit: stop ignoring failure to create temporary files
Something has changed in the Rocky Linux 10 environment that causes this
code to fail to compile:

  [ 61%] Building CXX object cmd/gvedit/CMakeFiles/gvedit.dir/csettings.cpp.o
  /builds/graphviz/graphviz/cmd/gvedit/csettings.cpp: In function
    'QString buildTempFile()':
  /builds/graphviz/graphviz/cmd/gvedit/csettings.cpp:316:16: error: ignoring
    return value of 'bool QTemporaryFile::open()', declared with attribute
    'nodiscard' [-Werror=unused-result]
    316 |   tempFile.open();
        |   ~~~~~~~~~~~~~^~
  In file included from /usr/include/qt6/QtCore/QtCore:275,
                   from /usr/include/qt6/QtWidgets/QtWidgetsDepends:3,
                   from /usr/include/qt6/QtWidgets/QtWidgets:3,
                   from /builds/graphviz/graphviz/cmd/gvedit/imageviewer.h:15,
                   from /builds/graphviz/graphviz/cmd/gvedit/mdichild.h:15,
                   from /builds/graphviz/graphviz/cmd/gvedit/csettings.cpp:18:
  /usr/include/qt6/QtCore/qtemporaryfile.h:52:32: note: declared here
     52 |     QFILE_MAYBE_NODISCARD bool open() { …
        |                                ^~~~
  cc1plus: all warnings being treated as errors

It is unclear to me exactly what has changed to cause this, because
neither the compiler nor Qt version have been upgraded. We could
suppress this failure, but instead lets just handle the condition it is
complaining about.

The function modified here is apparently OK with silent failure as it
does not check the return value of `loadPreview`. So we assume silent
failure when failing to create the temporary file is also OK.