smyrna updateSmGraph: remove unused 'totalElength'
The last use of this was removed in
17c8789fadf84dfc9a75185bd3b0b90452a26f0d. This is causing compilation to
fail in CI on Fedora 44:

  cmd/smyrna/topviewfuncs.c:758:11: error: variable 'totalELength' set
    but not used [-Werror=unused-but-set-variable=]
  758 |     float totalELength=0;
      |           ^~~~~~~~~~~~

Reported-by: GCC 16.1.1 -Wunused-but-set-variable