smyrna load_attr_list: remove unused 'i'
The last use of this was removed in
e3ddf2bb7d8b13a67d2921ac5d9d5df823ba5cbf. This is causing compilation to
fail in CI on Fedora 44:

  cmd/smyrna/gui/frmobjectui.c:502:21: error: variable 'i' set but not
    used [-Werror=unused-but-set-variable=]
  502 |         for (size_t i = 0; fgets(buffer, sizeof(buffer), file) != NULL; ++i) {
      |                     ^

Reported-by: GCC 16.1.1 -Wunused-but-set-variable