common cell_items: avoid function type casting
The type cast here technically violates strict aliasing. There is some
evidence that recent compilers will begin to detrimentally optimize code
like that prior to this change.¹ Additionally newer versions of Clang
have begun complaining about type casts like these:

  graphviz/lib/common/htmllex.c:464:15: error: cast from
    'int (*)(htmldata_t *, char *)' to 'attrFn' (aka
    'int (*)(void *, char *)') converts to incompatible function type
    [-Werror,-Wcast-function-type-strict]
  464 |     {"align", (attrFn) halignfn},
      |               ^~~~~~~~~~~~~~~~~

Note that this involved restructuring some HTML cell functions to
operate on `htmldata_t *` instead, the first member of `htmlcell_t`.

¹ https://gcc.gnu.org/gcc-14/porting_to.html#incompatible-pointer-types

Gitlab: #2840
Reported-by: Apple Clang 17.0.0.17000013 -Wcast-function-type-strict