core plugin json_end_graph: avoid casting function pointers
The type casts here technically violates strict aliasing. There is some
evidence that recent compilers will begin to detrimentally optimize code
like that prior to this change.¹ Additionally newer versions of Clang
have begun complaining about type casts like these:

  plugin/core/gvrender_core_json.c:706:14: error: cast from 'int
    (*)(GVJ_t *, const char *)' (aka 'int (*)(struct GVJ_s *, const char
    *)') to 'putstrfn' (aka 'int (*)(void *, const char *)') converts to
    incompatible function type [-Werror,-Wcast-function-type-strict]
    706 |         io.putstr = (putstrfn)gvputs;
        |                     ^~~~~~~~~~~~~~~~
  plugin/core/gvrender_core_json.c:707:13: error: cast from 'int
    (*)(GVJ_t *)' (aka 'int (*)(struct GVJ_s *)') to 'flushfn' (aka 'int
    (*)(void *)') converts to incompatible function type
    [-Werror,-Wcast-function-type-strict]
    707 |         io.flush = (flushfn)gvflush;
        |                    ^~~~~~~~~~~~~~~~

¹ https://gcc.gnu.org/gcc-14/porting_to.html#incompatible-pointer-types

Gitlab: #2840
Reported-by: Apple Clang 17.0.0.17000013 -Wcast-function-type-strict