CMake: suppress libgd discovery when found version is too low
The CMake+MinGW jobs have begun failing in CI:

  …
  -- Found GD: C:/msys64/mingw64/lib/libgd.dll.a
  -- Checking for module 'gdlib>=2.0.33'
  --   Package dependency requirement 'gdlib >= 2.0.33' could not be satisfied.
  Package 'gdlib' has version '..', required version is '>= 2.0.33'
  …
  FAILED: [code=1] tclpkg/gdtclft/libgdtclft.dll tclpkg/gdtclft/libgdtclft.dll.a
  C:\Windows\system32\cmd.exe /C "cd . && C:\msys64\mingw64\bin\cc.exe -Wall -Wcast-function-type -Wformat-overflow=2 -Wimplicit-fallthrough -Wmaybe-uninitialized -Wmissing-field-initializers -Wmissing-prototypes -Wshadow -Wundef -Wunused-parameter  -shared -o tclpkg\gdtclft\libgdtclft.dll -Wl,--out-implib,tclpkg\gdtclft\libgdtclft.dll.a -Wl,--major-image-version,0,--minor-image-version,0 tclpkg/gdtclft/CMakeFiles/gdtclft.dir/gdtclft.c.obj  C:/msys64/mingw64/lib/libgd.dll.a  C:/msys64/mingw64/lib/libtcl.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
  C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tclpkg/gdtclft/CMakeFiles/gdtclft.dir/gdtclft.c.obj:gdtclft.c:(.text+0x468): undefined reference to `GdPtrTypeSet'
  C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tclpkg/gdtclft/CMakeFiles/gdtclft.dir/gdtclft.c.obj:gdtclft.c:(.text+0x2b07): undefined reference to `GdPtrTypeSet'
  C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tclpkg/gdtclft/CMakeFiles/gdtclft.dir/gdtclft.c.obj:gdtclft.c:(.data+0x18): undefined reference to `GdPtrTypeUpdate'
  C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tclpkg/gdtclft/CMakeFiles/gdtclft.dir/gdtclft.c.obj:gdtclft.c:(.data+0x20): undefined reference to `GdPtrTypeSet'

It is unclear to me exactly what the root cause of this is, but I would
guess it is related to a recent libgd release.¹ Note that, in the above
trace, the version of libgd is somehow misreported. Another data point
is that the Autotools+MinGW jobs still appear to be passing.

Rather than try to indirectly debug this, lets just disable libgd
discovery if it reports a malformed version.

¹ https://github.com/msys2/MINGW-packages/commit/0268fe3b4584fccdf5f28e33e0d63cfbbf133585