gvc line_callback: avoid laundering pointer through 'strstr'
Newer compilers in combination with newer libc headers are clever enough
to understand const propagation through functions like `strstr` and thus
warn when const-ness of argument and result do not match:

  lib/gvc/gvconfig.c: In function 'line_callback':
  lib/gvc/gvconfig.c:276:16: error: initialization discards 'const'
    qualifier from pointer target type [-Werror=discarded-qualifiers]
    276 |    char *tmp = strstr(p, "/libgvc.");
        |                ^~~~~~

This change rephrases the code to preserve const correctness.

Reported-by: GCC 15.2.0 -Wdiscarded-qualifiers